import json
import scrapy
from scrapy.utils.project import get_project_settings  # Add this import
from sreality.items import SrealityItem


class SrealitySpider(scrapy.Spider):
    """Spider for scraping real estate data from Sreality website."""

    name = "sreality"

    # Load settings from settings.py
    custom_settings = get_project_settings()

    # Use the loaded settings
    url_pattern = custom_settings.get("SREALITY_URL")
    number_of_items = int(custom_settings.get("SREALITY_NUMBER_OF_ITEMS"))

    actual_page = 0
    actual_items = 0

    @property
    def next_url(self):
        """Generate the URL for the next page based on the URL pattern and current page number."""
        self.actual_page += 1
        return self.url_pattern.format(self.actual_page)

    def start_requests(self):
        """Initialize the scraping by yielding requests to the URLs generated by next_url()."""
        while self.actual_items < self.number_of_items:
            url = self.next_url
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        """Parse the JSON response and extract real estate data, yielding SrealityItem items."""
        json_data = json.loads(response.text)

        for estate in json_data['_embedded']['estates']:
            if self.actual_items >= self.number_of_items:
                break

            images = estate.get('_links', {}).get('images', [])
            self.actual_items += 1
            yield SrealityItem(
                title=estate.get("name"),
                images=[image['href'] for image in images]
            )
